- name: Instalar Docker y dependencias
  apt:
    name: ['docker.io', 'docker-compose', 'git', 'python3-pip']
    state: present
    update_cache: yes

- name: Copiar código de microservicios
  synchronize:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/"
  with_items:
    - ../../../../user-service
    - ../../../../product-service

- name: Copiar docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ ansible_user }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: 0644

- name: Levantar servicios
  shell: docker-compose up -d
  args:
    chdir: "/home/{{ ansible_user }}"